# Generated by Django 6.1.1 on 2026-09-22 08:00

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('New Product - awaiting to receive', 'New Product - awaiting to receive'), ('New Product - to be processed', 'New Product - to be processed'), ('Under Consideration - being processed', 'Under Consideration - being processed'), ('Will be listed - being prepared', 'Will be listed - being prepared'), ('Will NOT Be listed', 'Will NOT Be listed'), ('Created - waiting to go live', 'Created - waiting to go live'), ('Activated / Live', 'Activated / Live')], max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('supplierProductName', models.CharField(blank=True, max_length=255)),
                ('sampleReceived', models.DateField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255)),
                ('imagesLocation', models.CharField(blank=True, max_length=500)),
                ('imagesNote', models.CharField(blank=True, max_length=500)),
                ('tastingNotes', models.TextField(blank=True)),
                ('supplierDescription', models.TextField(blank=True)),
                ('nutritionalsReceived', models.BooleanField(default=False)),
                ('nutritionalsACP', models.BooleanField(default=False)),
                ('shelfLife', models.CharField(blank=True, max_length=255)),
                ('features', models.CharField(blank=True, max_length=255)),
                ('unitsPerBox', models.PositiveIntegerField(blank=True, null=True)),
                ('supplierAvailableFrom', models.DateField(blank=True, null=True)),
                ('supplierProductCode', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sellWholesale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sellACS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acpProductCode2', models.CharField(blank=True, max_length=255)),
                ('qblueProductName', models.CharField(blank=True, max_length=255)),
                ('b2bProductName', models.CharField(blank=True, max_length=255)),
                ('loadedQblue', models.BooleanField(default=False)),
                ('imgB2BNew', models.BooleanField(default=False)),
                ('imgB2BNoNew', models.BooleanField(default=False)),
                ('imgPrint', models.BooleanField(default=False)),
                ('createdB2B', models.BooleanField(default=False)),
                ('createdQblue', models.BooleanField(default=False)),
                ('status_changed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_row_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('nutrition', 'Nutrition Label')], max_length=16)),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='products_pr_active_7d1f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status_changed_at'], name='products_pr_status__8cd8bc_idx'),
        ),
    ]
