# Generated by Django 6.1.1 on 2026-09-22 08:06

import products.models
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_path, validators=[products.validators.validate_image_file_size]),
        ),
    ]
