# Generated by Django 6.1.1 on 2026-09-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdQblue',
        ),
    ]
