# Generated by Django 6.1.1 on 2026-09-23 20:00

import django.utils.timezone
import products.models
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_createdqblue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_nutrition_folder_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_product_folder_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productimage',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='drive_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='drive_thumbnail_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=products.models.product_image_upload_path, validators=[products.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
