# Generated by Django 6.1.1 on 2026-09-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_drive_photo_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plannedLaunch',
            field=models.TextField(blank=True),
        ),
    ]
